spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    com.test.newsmanagement: DEBUG
---
spring:
  profiles: production
server:
  servlet:
    context-path: /newsManagement
logging:
  level:
    root: INFO
    com.test.newsmanagement: DEBUG
