spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  output:
    ansi:
      enabled: always
---
spring:
  profiles: production


