CREATE TABLE news(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL
);

CREATE TABLE comments(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    date DATE NOT NULL,
	text TEXT NOT NULL,
    username VARCHAR(32) NOT NULL,
	id_news BIGINT,
	CONSTRAINT fk_news FOREIGN KEY (id_news) REFERENCES news(id)
);